INFO     DEFAULT:driver_config.py:22 appium -p 4725 -bp 6725 -U 5483e9c3 --log-timestamp --local-timezone
INFO     DEFAULT:driver_config.py:32 读取配置文件成功
INFO     DEFAULT:driver_config.py:33 {'platformName': 'Android', 'appPackage': 'com.xueqiu.android', 'appActivity': '.view.WelcomeActivityAlias', 'unicodeKeyboard': True, 'resetKeyboard': True, 'autoGrantPermissions': True, 'noReset': True, 'newCommandTimeout': 120}
INFO     DEFAULT:driver_config.py:51 {'platformName': 'Android', 'deviceName': '5483e9c3', 'appPackage': 'com.xueqiu.android', 'platformVersion': '7.1.2', 'appActivity': '.view.WelcomeActivityAlias', 'unicodeKeyboard': True, 'resetKeyboard': True, 'newCommandTimeout': 120, 'systemPort': 6725, 'noReset': True, 'autoGrantPermissions': True}
INFO     DEFAULT:driver_config.py:52 http://localhost:4725/wd/hub
WARNING  urllib3.connectionpool:connectionpool.py:745 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x110431dd0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:745 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11053ccd0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:745 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1105ce0d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session